---

  - name: Nginx setup
    apt: pkg=nginx state=present

  - name: Installing dependencies for Mariadb
    apt: name=software-properties-common

  - name: Add repository key to the system
    shell: sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'


  - name: Install MariaDB repository 10.3
    apt_repository: repo='deb [arch=amd64] http://mirror.zol.co.zw/mariadb/repo/10.3/ubuntu xenial main' state=present


  - name: update
    apt: update_cache=yes
    ignore_errors: yes

  - name: Install MariaDB Server 10.3
    apt: name=mariadb-server state=latest

  - name: Install MariaDB Client 10.3
    apt: name=mariadb-client state=latest

  - name: PHP
    apt: name=software-properties-common

  - name: Add PHP 7.2 PPA repository
    apt_repository:
      repo: 'ppa:ondrej/php'

  - name: install php with dependencies
    apt: pkg={{ item }} state=latest
    with_items:
    - git
    - php7.2
    - php7.2-fpm
    - php7.2-mysql
    - php7.2-gd
    - php7.2-ldap
    - php7.2-mbstring
    - php7.2-curl
    - python3-mysqldb
    - php7.2-bcmath
    - php7.2-curl
    - php7.2-gmp
    - php7.2-zip
    - php7.2-xml
    - libapache2-mod-php7.2
    - php7.2-common
    - php7.2-intl
    - php7.2-sqlite3

  - name: Install curl
    become: true
    shell: apt install curl


  - name: Download composer
    become: true
    shell: curl -sS https://getcomposer.org/installer |  php -- --install-dir=/usr/local/bin --filename=composer

