---
- hosts: localhost
  become: yes
  vars_files:
    - /home/ubuntu/snipeit-ansible-uzma/vars/main.yml

  tasks:
  - name: Update
    apt: update_cache=yes

  - name: installation file
    include: installation.yml

  - name: configuring file
    include: snipe-it.yml
